name: topologic_py39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  # opencascade
  - occt=7.7.0
  # build tools
  - cxx-compiler
  - cmake
  - ninja
  - pip:
    - auditwheel ; platform_system == "Linux"
    - patchelf ; platform_system == "Linux"
    - delocate
    - machomachomangler  ; platform_system == "Windows"
    - pefile  ; platform_system == "Windows"
